import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show FilteringTextInputFormatter;
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'package:sou9ix/shared/core/theme/app_colors.dart';
import 'package:sou9ix/shared/core/theme/app_theme.dart';
import 'package:sou9ix/shared/features/settings/service/company_code_service.dart';
import 'package:sou9ix/shared/features/settings/service/shop_code_storage.dart';
import 'package:sou9ix/shared/features/settings/viewmodel/shop_code_provider.dart';

/// Shown once, on this device's very first Caissier-app launch — links the
/// install to a shop by its permanent join code (see [CompanyCodeService],
/// generated by the admin at signup and always visible on their Profil
/// page). Once validated, the code is cached locally
/// ([ShopCodeStorage]) and [SplashScreen] skips straight to `/login` on
/// every later launch.
class EnterShopCodeScreen extends ConsumerStatefulWidget {
  const EnterShopCodeScreen({super.key});

  @override
  ConsumerState<EnterShopCodeScreen> createState() =>
      _EnterShopCodeScreenState();
}

class _EnterShopCodeScreenState extends ConsumerState<EnterShopCodeScreen> {
  final _codeCtrl = TextEditingController();
  bool _loading = false;
  String? _error;

  @override
  void dispose() {
    _codeCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final typed = _codeCtrl.text.trim().toUpperCase();
    if (typed.isEmpty) {
      setState(() => _error = 'Entrez le code de votre magasin.');
      return;
    }
    setState(() {
      _loading = true;
      _error = null;
    });

    try {
      final exists = await ref
          .read(companyCodeServiceProvider)
          .shopCodeExists(typed);
      if (!exists) {
        if (!mounted) return;
        setState(() {
          _loading = false;
          _error = 'Code introuvable — vérifiez-le auprès de votre admin.';
        });
        return;
      }
      await ShopCodeStorage.save(typed);
      ref.read(shopCodeProvider.notifier).state = typed;
      if (mounted) context.go('/login');
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _loading = false;
        _error =
            'Impossible de vérifier ce code — vérifiez votre connexion internet et réessayez.';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: LayoutBuilder(
          builder: (context, constraints) {
            return SingleChildScrollView(
              padding: const EdgeInsets.fromLTRB(24, 24, 24, 24),
              child: ConstrainedBox(
                constraints: BoxConstraints(minHeight: constraints.maxHeight),
                child: IntrinsicHeight(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 12),
                      Container(
                            width: 64,
                            height: 64,
                            decoration: BoxDecoration(
                              gradient: AppColors.tealGradient,
                              borderRadius: BorderRadius.circular(AppRadius.md),
                              boxShadow: [
                                BoxShadow(
                                  color: AppColors.teal.withValues(alpha: 0.18),
                                  blurRadius: 14,
                                  offset: const Offset(0, 6),
                                ),
                              ],
                            ),
                            child: const Icon(
                              Icons.qr_code_rounded,
                              color: Colors.white,
                              size: 30,
                            ),
                          )
                          .animate()
                          .fadeIn(duration: 400.ms)
                          .scale(begin: const Offset(0.7, 0.7)),
                      const SizedBox(height: 24),
                      Text(
                        'Bienvenue 👋',
                        style: Theme.of(context).textTheme.displaySmall,
                      ).animate().fadeIn(delay: 100.ms).slideX(begin: -0.05, end: 0),
                      const SizedBox(height: 6),
                      Text(
                        'Entrez le code du magasin fourni par votre administrateur.',
                        style: Theme.of(context).textTheme.bodyMedium,
                      ).animate().fadeIn(delay: 180.ms),
                      const SizedBox(height: 32),
                      TextField(
                        controller: _codeCtrl,
                        autofocus: true,
                        textCapitalization: TextCapitalization.characters,
                        inputFormatters: [
                          FilteringTextInputFormatter.allow(RegExp(r'[A-Za-z0-9-]')),
                        ],
                        style: const TextStyle(
                          fontWeight: FontWeight.w800,
                          letterSpacing: 1.5,
                        ),
                        decoration: InputDecoration(
                          labelText: 'Code du magasin',
                          hintText: 'Ex. S9X-4F82A',
                          prefixIcon: const Icon(
                            Icons.storefront_outlined,
                            size: 20,
                          ),
                        ),
                        onChanged: (_) => setState(() => _error = null),
                        onSubmitted: (_) => _loading ? null : _submit(),
                      ).animate().fadeIn(delay: 220.ms).slideY(begin: 0.15, end: 0),
                      if (_error != null) ...[
                        const SizedBox(height: 10),
                        Text(
                          _error!,
                          style: const TextStyle(
                            color: AppColors.danger,
                            fontWeight: FontWeight.w600,
                            fontSize: 12.5,
                          ),
                        ),
                      ],
                      const SizedBox(height: 22),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton(
                          onPressed: _loading ? null : _submit,
                          child: _loading
                              ? const SizedBox(
                                  width: 22,
                                  height: 22,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2.4,
                                    color: Colors.white,
                                  ),
                                )
                              : const Text('Continuer'),
                        ),
                      ).animate().fadeIn(delay: 280.ms).slideY(begin: 0.15, end: 0),
                      const Spacer(),
                      const SizedBox(height: 24),
                      Center(
                        child: Column(
                          children: [
                            Text(
                              'Sou9ix',
                              style: TextStyle(
                                color: AppColors.textSecondary,
                                fontWeight: FontWeight.w800,
                                fontSize: 13,
                              ),
                            ),
                            const SizedBox(height: 2),
                            Text(
                              'Gérez votre commerce simplement',
                              style: TextStyle(
                                color: AppColors.textFaint,
                                fontSize: 11.5,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
