// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0t-dWDDdLzRyu9AlgKosmQTqfh0qrCLQ',
    appId: '1:886810735929:web:c396670b4cd8d1e82464e8',
    messagingSenderId: '886810735929',
    projectId: 'sou9ix',
    authDomain: 'sou9ix.firebaseapp.com',
    storageBucket: 'sou9ix.firebasestorage.app',
    measurementId: 'G-8ZEP2JJRFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3Ym1aMlv63O5YBw9h8zV-StVQ_QMocw',
    appId: '1:886810735929:android:fc798bebd91a2fa22464e8',
    messagingSenderId: '886810735929',
    projectId: 'sou9ix',
    storageBucket: 'sou9ix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDML41Wucwc13buxcB_8Sc01YPXnhy7XLM',
    appId: '1:886810735929:ios:e5d50e347a63c3922464e8',
    messagingSenderId: '886810735929',
    projectId: 'sou9ix',
    storageBucket: 'sou9ix.firebasestorage.app',
    iosBundleId: 'com.sou9ix.sou9ix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0t-dWDDdLzRyu9AlgKosmQTqfh0qrCLQ',
    appId: '1:886810735929:web:c64f96b3d65552322464e8',
    messagingSenderId: '886810735929',
    projectId: 'sou9ix',
    authDomain: 'sou9ix.firebaseapp.com',
    storageBucket: 'sou9ix.firebasestorage.app',
    measurementId: 'G-RGHD3EYF9S',
  );
}
